ASK WHERE {
  <http://rdfa.digitalbazaar.com/test-suite/test-cases/html4/0127.html> <http://example.org/test1> "Test 1 ".
  <http://rdfa.digitalbazaar.com/test-suite/test-cases/html4/0127.html> <http://example.org/test2> "Test 2  ".
}
