ASK WHERE {
	<http://rdfa.digitalbazaar.com/test-suite/test-cases/xhtml11/0063.html> <http://www.w3.org/1999/xhtml/vocab#prev> <http://rdfa.digitalbazaar.com/test-suite/test-cases/xhtml11/0062.html> .
}